### ISSUE TITLE
Dupe glitch

### ISSUE THREAD

**Issue by sandor111** [Qballl/StaffPlus#110]
https://youtu.be/Tlj2BIU0UGM

**Comment by Azoraqua** [comment]
Alright, thanks for notifying us. We'll take a look into it.

**Comment by Qballl** [comment]
Fixed it. Now you cannot interact with a chest's inventory when in staffmode you can only view them for now at least

**Comment by sandor111** [comment]
Thought this was fixed but it gives this error on my 1.8 server:
`[20:21:53] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to StaffPlus v3.3.1.0
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[server.jar:git-PaperSpigot-"4c7641d"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[server.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [server.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [server.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228) [server.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInteractManager.java:463) [server.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:763) [server.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [server.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [server.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-PaperSpigot-"4c7641d"]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [server.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [server.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [server.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [server.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [server.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/block/Container
	at net.shortninja.staffplus.server.listener.player.PlayerInteract.onInteract(PlayerInteract.java:86) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[server.jar:git-PaperSpigot-"4c7641d"]
	... 18 more
Caused by: java.lang.ClassNotFoundException: org.bukkit.block.Container
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92) ~[server.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[server.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
	at net.shortninja.staffplus.server.listener.player.PlayerInteract.onInteract(PlayerInteract.java:86) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[server.jar:git-PaperSpigot-"4c7641d"]
	... 18 more`

**Comment by sandor111** [comment]
Has this been fixed?

**Comment by sandor111** [comment]
@Qballl I saw you made some commits, does that fix this issue?

**Comment by Qballl** [comment]
I dont think so most of those have been MySQL related things

**Comment by sandor111** [comment]
> I dont think so most of those have been MySQL related things

Do you have time to look into it? Ppl have been using this bug to dupe items for a long time.

**Comment by sandor111** [comment]
Hm neither of the configuration options:
  inventory-interaction: true
  item-change: false

Can temporarly fix the issue, currently there is nothing I can do to prevent staff from abusing this issue.

**Comment by sandor111** [comment]
Still happening @Qballl

**Comment by Qballl** [comment]
Did you grab the latest one from spigot b/c I tested it and was not able to drag items

**Comment by sandor111** [comment]
> Did you grab the latest one from spigot b/c I tested it and was not able to drag items

I didn’t test yet on my 1.8 server but I didn’t see any commits related to the error so pretty sure the latest dev version still has this issue. This is the error btw:
Caused by: java.lang.NoClassDefFoundError: org/bukkit/block/Container

**Comment by Qballl** [comment]
Thats because I just did one large push on dev branch and that should be fixed too try updating

**Comment by sandor111** [comment]
> Thats because I just did one large push on dev branch and that should be fixed too try updating
Could you send me the compiled dev version for 1.8?

**Comment by sandor111** [comment]
Confirmed, works on 1.8

**Comment by sandor111** [comment]
@Qballl still not fixed, I was confused when I said it was fixed; I tried dragging the items in staffmode which didn’t work but this is not the issue. In the yt video I send at the start of this thread the issue can be seen:
https://youtu.be/Tlj2BIU0UGM

**Comment by Qballl** [comment]
Can you verify if it's now fixed until then I will reopen issue.

**Comment by Qballl** [comment]
Closing due to inactivity.
